package com.hkm.rpgcorner

object RPGsData {
    private val rpgNames = arrayOf("Xenoblade Chronicles™: Definitive Edition",
        "FINAL FANTASY VII REMAKE",
        "Dark Souls III",
        "The Witcher 3: Wild Hunt",
        "Maneater",
        "Mount & Blade II: Bannerlord",
        "Persona 5 Royal",
        "The Outer Worlds",
        "Kingdom Hearts III",
        "Divinity: Original Sin 2 - Definitive Edition")

    private val rpgDetails = arrayOf("In many of the ways that really matter, Xenoblade Chronicles Definitive Edition delivers. It takes an incredible RPG - one that could lay claim to being among the best of the last decade - and makes small, considered tweaks in all the right places. It serves the mad, magical majesty of Xenoblade Chronicles' world, staying entirely faithful to the original while gently polishing it for its HD debut - a little too gently in some places, you might argue.\n\nAnd what a world it is! Xenoblade Chronicles' grand concept, and its execution, remains an all-time great. The story it serves is just fine, weaving in Takahashi's recurring themes; gods will fall and fates will be altered, all at the blade of a blonde-haired hero who sounds like a junior estate agent from Swindon (I'm afraid I'm not a fan of the localised voice work in Xenoblade Chronicles, but at least you can switch to the Japanese voice track at any point in this Definitive Edition, and fans will be delighted that Jenna Coleman reprises her role as Melia for the additional content offered in this Definitive Edition).\n\nIt's not about the story, though, and more about the places it takes you. In the most wide-eyed, excitable terms possible - and I don't know how else you talk about something as fantastic as this - it's a world set on the back of two warring, country-sized titans, the pair trapped in stony stasis for many years. So you begin on the wide-open grassy plains on the calf of a god's outstretched leg then slowly work your way up. Size is everything here - the maps you explore are vast, open-ended spaces drawn with the verve and imagination of pulpy sci-fi's best cover artists. From the sun-scorched grass of Gaur Plain to the frosted starlight of Valak Mountain by night, Xenoblade Chronicles is a heady delight to explore and discover.",
        "It's no easy task to rewrite one of the most beloved stories in videogame history, and given the series' recent shaky past even Final Fantasy 7's most optimistic fans were nervous as to how their favourite characters, moments and story arcs would weather the transition. But I'm happy to say that, for the most part at least, the spirit and tone of the original Final Fantasy 7 is perfectly preserved. Dare I say it, the remake even manages to frequently improve upon the original's telling of the story.\n\nCharacters you know and love are fizzing with new life and personality, their expressions and movements and little asides capturing the essence of what made them so iconic and enduring. Even the dialogue - which some feared would be stilted given a few previews - mostly hits the mark. There are plenty of laugh-out-loud moments as the party chat, bicker, and get to know one another on their journey. And this is also one of the thirstiest games I think I've ever played - Square knows exactly what it's doing as it toys with your affections, making you fall in love with one character after another. If I had my way it wouldn't be so much a love triangle as a love decagon.\n\nThis Remake is respectful of the original Final Fantasy 7 for the majority of its runtime, right down to specific lines of dialogue being said just so and NPCs being dressed a certain way But it has made a lot of changes too - some small, some story-alteringly huge. The Wall Market, for example, retains most of the little narrative details that made the place so special and fun to explore, but these details have been reworked so that even if, like me, you know the original like the back of your buster sword, exploring those neon-tinged backstreets isn't without some surprises. Bigger narrative beats have been reworked - I won't spoil them here - and it's too early to say whether they've changed things for better or for worse, but they have changed things. The implications for the second part of this project could be absolutely massive is all I'll say.",
        "Dark Souls was a world where history had already happened over hundreds of years, and you as the Chosen Undead were learning about it by picking through the debris. In Dark Souls 3 this long-term wear and tear is applied to the Lordran we knew. Firelink Shrine is the first of what will be many environmental callbacks, each bearing the weight of centuries and many changed beyond recognition. Some areas have been built-upon, layers of stone swaddling the original architecture nearly beyond recognition, while others have been looted or transplanted over the years, and relics of the world past are in new homes.\n\nMost of us will need it. There are surprises in how From Software has approached Dark Souls 3 and one is the incredible challenge it offers, to the extent an early patch toning certain elements down would be no surprise. I know these games well but, even allowing for ring-rust, was simply knocked flat by many enemies and bosses time and again. Part of this is Dark Souls 3 working with a familiar combat system, and several returning enemy types, which has led to an increase in what it expects from the player. Later enemies are relentless and clumped in groups so it's not uncommon to be simply harried to death, boxed-in by constant blows or unseen assailants, and mercilessly finished-off every time you go for a panic chug of health-giving Estus.\n\nThe big reason behind this increase in enemy aggression, I would hazard, is Bloodborne. The greatest game of 2015, also developed by From Software and directed by Hidetaka Miyazaki, was a Souls-alike, in the sense of sharing the same foundation but using this to create a much more offensive combat system based around transforming ('trick) weapons. Bloodborne's battles are fluid, intense, and tremendously exciting - as an arch in-game description notes, \"shields are nice, but not if they engender passivity.\" And it's in this context that Dark Souls 3 returns to the classic sword-and-shield combat of the Souls games.",
        "In its five years of existence, it is evident that a good number of players go back to The Witcher 3 over and over. The primary reason for this lies in the game's excellent development, which is a culmination of various elements that worked well both individually and as one piece. The game sports impressive visuals that give life to its massive open-world setting, where players can spend countless hours busying themselves with various quests.\n\nThe story of the game is simple; Geralt of Rivia, who is a Witcher or someone who hunts monsters, is on a quest to find his adoptive daughter Ciri, who is being pursued by the Wild Hunt. For those unfamiliar, The Wild Hunt is a group of wraiths on undead horses who are scouring the world to find slaves to serve the Alder Folk, and to complicate matters, Ciri is also the real daughter of Emhyr var Emreis and is the sole princess of Cintra. The game branches out from the quest to find Ciri and players soon find themselves in a world that is very alive and immersive, with various side quests and interesting characters to interact with.\n\nApart from an immersive story and well fleshed out characters, The Witcher 3 also offers a massive amount of quests that players can embark on and have a better understanding of the game's history and lore. Most quests also offer Witcher 3 players a tough decision at the end, and each choice will have an on how the game will play out. On average, a single playthrough of The Witcher 3 can take up to 70-80 hours long due to its extensive main story and over a hundred different side missions that players can participate in.\n\nAnother aspect of The Witcher 3 that makes it popular to this day is its awesome cast of characters, including the villains. Although not all villains in The Witcher 3 can be engaged in combat, it doesn't make them any less menacing. These villains certainly give color to the overall story of the game, especially with their evil actions and motivations. Again, while every player will have their favorite baddie, here are some of the most popular Witcher 3 villains that were memorable and left a long-lasting impact on Witcher fans.",
        "You play, as you’ve probably gathered, as a shark. And you’ll absolutely need to play with a controller, as you’re zooming around in three dimensions, flipping from the water and jackknifing in order to do murders or avoid them. Apart from anything else, you’d be missing out without the gritty haptic rumble through your hands as your shark GASHUNKK-GASHUNKK-GASHUNKKs its way through fish, turtles, humans and the hulls of boats. You can lunge, leap, roll, thrash, and do this completely mental thing where you use your tail to welly things in your mouth fifty feet into the air.\n\nIt’s properly gruesome, too, with blood-clouded water, flesh chunks and all. Real hashtag-fat-blood stuff (a little RPS podcast joke for you there). There’s constant roaring, even though sharks cannot roar, and it evokes the sort of feelings that leave review writers struggling to find alternatives to the word “visceral”. There is a predictably sadistic pleasure to be taken in mauling defenceless human swimmers, of course. They scream and flail and flop, and the game encourages you to inflict the most primal horrors imaginable on them. Apart from anything else, after umpteen infuriating dogfights with alligators, there’s a lot of catharsis to be had in letting it all out on something that can’t fight back.\n\nThe other thing in Maneater that really made me long for it to be something else was its environment design, which is intermittently stellar. The underwater landscapes are superbly detailed, with tangled fallen trees, vegetation, reed beds and murk evoking real settings, and more polluted urban waterways feeling genuinely apocalyptic in their profusion of rubbish in the water column. The lighting effects, particularly at sundown, are gorgeous, and the shark – as one would hope – is fantastically modelled, with the same bulbous, surging strength as the real deal. Even the music, at times, is way better than it had to be, with orchestral swells when you reach the upgrade hubs called “grottoes”, and the classic anxiety celloes when there’s danger afoot.",
        "Mount & Blade was terrific fun immediately. I’ve surely regaled some of you in the comments over the years about how I played its 6-level demo all night, over and over, just fighting endlessly in the Zendar arena. Buying it then was inevitable, even though it was openly unfinished, a novel concept several years before Minecraft and then the rest of the industry gave the process an offical name. There was other stuff to do out in the world, but the core of it, that fantastic, exciting, chaotic combat, was there very early on. The rest of the world stuff – the new factions, the banners, the conquest, the villages, and the sucking up to 300 tedious lords – that came later, and it was fine, mostly. Given the choice, I skipped most of it.\n\nFundamentally, Bannerlord is the same as Warband, the spruced-up and expanded 2010 reissue of Mount & Blade most people refer to. That’s absolutely fine, and exactly what TaleWorlds said it would be. You create a character, giving them a variety of martial or mental skills depending on what sort of playstyle you’re going for, and then wander a huge world map looking for people to recruit to your army, and other people to shove into the mud and jump up and down on. When you cross a hostile force you enter a full 3D battle in which you run about stabbing, spearing, and shooting foes, or sitting back and yelling at your dudes, or both.\n\nThe combat is very much the same as it always was, but much shinier and fiercer. The total removal of automated directional blocking is a controversial decision (compounded by a poorly conceived tutorial fight that can thankfully be skipped entirely), but it can be mitigated somewhat by not bumping the difficulty up to begin with. I find it bizarre that the hovering indicators and the frankly offensive crosshairs are all togglable, but the difficult blocking isn’t. It does, I suppose, make shields far more valuable.",
        "Given its two predecessors received enhanced versions, there was always a presumption that Persona 5, RPGamer’s 2017 Game of the Year, would receive the same treatment. The expectation came true with Persona 5 Royal, though unlike its predecessors the new version arrived just three years later without hitting a new platform. Enhancing an already fantastic and well-loved title, Persona 5 Royal offers undoubtedly the definitive version of the game; its new content adding a good amount of freshness, while tweaks elsewhere ensure it keeps even more in step with players. The sheer size and lack of a massive game-changer might make it a challenge to persuade some to relive the experience, but for any potential new recruits it’s the perfect way to join the Phantom Thieves, as well as for past players to jump back in.\n\nRather than creating a fictional Japanese town like its predecessors, Persona 5 takes place in Tokyo making use of many familiar districts, particularly Shibuya. After an in media res intro, players control a young man sent to Tokyo at the start of April as part of a probation package after he is after he is unjustly convicted of assault in his unnamed home town. Enrolled at Shujin Academy, he quickly uncovers further injustice being perpetuated by PE teacher Suguru Kamoshida.\n\nPersona 5 Royal adds two new major characters — student gymnast Kasumi Yoshizawa and school counselor Takuto Maruki — whose stories are built up to across the year; Yoshizawa debuts right at the start, while Maruki comes into the picture after the fallout involving Kamoshida. Otherwise the primary story remains unchanged up until the newly added arc at the end, but there’s certainly no problem with that. Persona 5’s tale involves the expected psychological and philosophical elements, but its larger focus on corruption and people manipulating others for their own benefits takes on even more poignancy now. Those who played through the original game may not find it enough to justify spending all those hours treading familiar territory to get there, but Royal’s new story section does an excellent job of following on from the original climax. It brings things back into a wider examination on the actions of the Phantom Thieves and potential extensions, and ends up resonating much better on a personal level than the original game’s finale.",
        "The Outer Worlds adopts the most compelling innovations of modern Fallout games, emphasising immersive exploration and impactful, action-oriented combat in a game engine (Unreal Engine) that actually makes those things feel good by contemporary standards. It shares Fallout's satirical but incredibly bleak look at the future, but is free of its tired tropes. Critically, The Outer Worlds exhibits the same depth of soul as the early Interplay and Black Isle Fallout games (as well as other games in the '90s PC RPG genre) with a genuinely complex, interconnected narrative web of relationships and events that feel like they can change in a seemingly infinite number of ways based on the character you want to be, the variety of choices you can make, and the actions you take.\n\nIn The Outer Worlds, you are just one of the thousands of people left in hibernation on an abandoned colony ship, when a scientist of possibly ill repute frees you and enlists your help in saving the rest of your frozen peers. After a rigorous character creation process--involving a slew of variable attributes, perks, and aesthetic customization--you crash-land on a planet, alone, and from there, how you make your mark on the Halcyon system is up to you.\n\nDespite having strong RPG foundations, the combat in The Outer Worlds is very much focussed on first-person action, incorporating things like parries, blocks, and dodges on top of an array of melee weapons and firearms. There's a hectic and fast-paced fluidity to combat that feels very good, however. That's aided by some enthusiastic sound design, which does most of the heavy lifting in giving all weapons some satisfying feedback. A range of \"Science weapons\" bring some creative diversity in your arsenal, and features guns that have unique, entertaining properties like shrinking enemies or turning them against each other.",
        "For all its intricacies, the underlying story is a fairly simple one. Our big-shoed hero, Sora, needs \"the power of waking\" to sort out regular villains Organization 13 - who with their ostentatious zips and hooded black leather trenchcoats look ever more like Dementors in a fetish club. The tone is set in the very first scene, which adopts the time-honoured tradition of representing the battle between good and evil as a game of chess between a man dressed in black and another in white. As one takes his turn, he asks the other the immortal question, \"Have you heard of the ancient Keyblade War?\"\n\nIt's a pity, as when Kingdom Hearts 3 deigns to let you play - and I'm not talking about the moments where a cutscene finishes and you walk forward for ten seconds only for another to start up - there's a liberal sprinkling of Disney magic. With a full magic gauge you can summon the likes of Simba, roaring to produce a circle of flame as you ride him into battle. Then, as you chain attacks, you can call upon the brilliant Attractions, each based on a fairground ride and decorated in thousands of tiny lights. A carousel spins faster and faster with rhythmic button presses; teacups careen madly around as you try to steer them towards clusters of enemies, laughing like a child. They're not always particularly efficient, though if used well they can be devastating. But gosh, they're fun.\n\nThat's typical of a game where you seem to spend more time watching than doing. Which would be less of a problem if the story worked. Nowhere are the script's failings more obvious than the third kingdom you visit: Corona, from the fantastic Tangled. Suddenly, the dialogue has more zip, the gags are finally landing - and that's because they're lifted wholesale from the film. In fact, sluggish editing takes the shine off one of its great early comic moments, which plays here like an early theatre rehearsal before everyone's properly learned their lines. The same goes for Frozen. Shortly after we meet Elsa, we get the whole of Let It Go, and if you weren't convinced before just how good that song is, here it sparkles like a diamond in the rough: a heart-melting moment of soaring brilliance.",
        "Divinity: Original Sin 2 lets you know it means business in the first few minutes of its story. Waking up tied to a surgical bench aboard a prison ship transporting \"Source-users\" (that’s mages, essentially) to the ironically named Fort Joy, your avatar is immediately faced with the first of a growing stack of choices: follow instructions and leave the room, or explore a little first. If you take the latter, this area acts as a tutorial of sorts, familiarising you with the basic commands and giving you a subsequent series of choices involving a prisoner in the hold and the guard watching him. Suffice to say, these early choices are really just a taste of things to come, but I was hooked right away.\n\nYou’ll spend as much time trying to sneak or talk your way out of combat as you will fighting, but the enemy encounters are often exhilarating affairs that marry elements of Dragon Age: Origins and Baldur’s Gate. Turn-based and tactical, combat is complicated and challenging in Divinity Original Sin 2, even when you’ve passed the 15 hour mark. There are so many skills, spells and elements to consider, along with distance to enemy, status effects, terrain, and elevation. An Ability Points system limits your movements and actions, and forces you to consider every turn carefully and, where possible, plan ahead. Even on Classic Mode battles can be trying, let alone Tactician Mode (which comes with an permadeath option, natch), and you’ll want to make friends with the Quicksave as early as possible.\n\nIt’s easy to overlook the majority of Divinity 2’s shortcomings because what it does well, it does incredibly well. I struggle to remember a game of this scope and with this much dialogue that’s so consistently well written and acted as this. There’s a vein of sardonic humour running through the whole narrative, riddled with in-jokes and Easter eggs, and peppered with self-aware black comedy. Likewise, the sheer number of consequence-heavy choices and narrative tangents is truly impressive. I mean, you can literally kill anyone you meet if you choose to – though I wouldn’t advise doing so unless you want to make the going decidedly uphill.\n\nPut simply, Larian studios have created an absolute belter, and despite a handful of caveats the crossover from PC to console is a resounding success. Thanks to the likes of Pillars of Eternity, Sword Coast Legends and, of course, this game’s predecessor, there’s no shortage of party-based tactical RPGs available on console these days, but I’d confidently champion Divinity Original Sin 2 as the best of damn good bunch.")

    private val rpgImages = arrayOf(R.drawable.xenocover,
        R.drawable.ff7cov,
        R.drawable.ds3cov,
        R.drawable.witcher3cov,
        R.drawable.maneatercov,
        R.drawable.bannerlordcov,
        R.drawable.p5rcov,
        R.drawable.outerworldcov,
        R.drawable.kh3cov,
        R.drawable.dos2cov)

    private val rpgStores = arrayOf(R.drawable.nswitch,
        R.drawable.ps4,
        R.drawable.steam,
        R.drawable.steam,
        R.drawable.epic,
        R.drawable.steam,
        R.drawable.ps4,
        R.drawable.epic,
        R.drawable.ps4,
        R.drawable.steam)

    private val rpgGameImages = arrayOf(R.drawable.xenoblade,
        R.drawable.ff7,
        R.drawable.ds3,
        R.drawable.witcher3,
        R.drawable.maneater,
        R.drawable.bannerlord,
        R.drawable.p5r,
        R.drawable.outerworld,
        R.drawable.kh3,
        R.drawable.dos2)

    private val rpgPrices = arrayOf("$59.99",
        "$59.99",
        "$59.99",
        "$39.99",
        "$14.99",
        "$49.99",
        "$59.99",
        "$44.99",
        "$59.99",
        "$44.99")

    private val rpgLinks = arrayOf("https://www.nintendo.com/games/detail/xenoblade-chronicles-definitive-edition-switch/",
        "https://store.playstation.com/en-id/product/JP0082-CUSA07052_00-FFVIIREMAKE00000",
        "https://store.steampowered.com/app/374320/DARK_SOULS_III/",
        "https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/",
        "https://www.epicgames.com/store/en-US/product/maneater/home",
        "https://store.steampowered.com/app/261550/Mount__Blade_II_Bannerlord/",
        "https://store.playstation.com/en-us/product/UP0177-CUSA17416_00-PERSONA5R0000000",
        "https://www.epicgames.com/store/en-US/product/the-outer-worlds/home",
        "https://store.playstation.com/en-id/product/UP0082-CUSA12031_00-ASIAFULLGAME0000",
        "https://store.steampowered.com/app/435150/Divinity_Original_Sin_2__Definitive_Edition/")

    private val rpgReviews = arrayOf("https://www.eurogamer.net/articles/2020-05-27-xenoblade-chronicles-definitive-edition-gently-re-touched-thoughtfully-expanded-take-on-a-modern-classic",
        "https://www.eurogamer.net/articles/2020-04-06-final-fantasy-7-remake-review-a-faithful-remake-with-a-few-missteps-along-the-way",
        "https://www.eurogamer.net/articles/2016-04-04-dark-souls-3-review",
        "https://gamerant.com/witcher-3-2020-classic-story-plot-villains-quests/",
        "https://www.rockpapershotgun.com/2020/05/22/maneater-review/",
        "https://www.rockpapershotgun.com/2020/04/08/mount-blade-ii-bannerlord-review-early-access/",
        "https://rpgamer.com/review/persona-5-royal-review/",
        "https://www.gamespot.com/reviews/the-outer-worlds-review-over-the-moon/1900-6417345/",
        "https://www.eurogamer.net/articles/2019-01-29-kingdom-hearts-3-review",
        "https://www.godisageek.com/reviews/divinity-original-sin-2-definitive-edition-review/")

    val listData: ArrayList<RPG>
        get() {
            val list = arrayListOf<RPG>()
            for (position in rpgNames.indices) {
                val rpg = RPG()
                rpg.name = rpgNames[position]
                rpg.detail = rpgDetails[position]
                rpg.photo = rpgImages[position]
                rpg.store = rpgStores[position]
                rpg.game = rpgGameImages[position]
                rpg.price = rpgPrices[position]
                rpg.link = rpgLinks[position]
                rpg.review = rpgReviews[position]

                list.add(rpg)
            }
            return list
        }
}